name: action-test

on:
  workflow_dispatch:
    inputs:
      foo:
      BAR:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Env vars
        env:
          cli-foo: ${{ inputs.foo }}
          cli-bar: ${{ inputs.bar }}
        run: |
         echo "Tenant-Name: ${cli-foo}"
         echo "Tenant-ID: ${cli-bar}"
     
      - name: Get env vars
        env:
         URL: ${{ secrets.URL }}
         USERNAME: ${{ secrets.USERNAME }}
        run: |
         echo "Base url: ${URL}"
         echo "User name : ${USERNAME}"
      #- name: Test Failure
      #  run: exit 1
